Import libraries and load the dataset

In [1]:
import pandas as pd
import re
import nltk
import string
import emoji

df = pd.read_csv('../data/mental_health_social_media_dataset.csv')
df.head()

   Unique_ID                                               text   status
0        0.0                                         oh my gosh  Anxiety
1        1.0  trouble sleeping, confused mind, restless hear...  Anxiety
2        2.0  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3        3.0  I've shifted my focus to something else but I'...  Anxiety
4        4.0  I'm restless and restless, it's been a month n...  Anxiety

Download and import **stopwords** and **tokenizer** tool

In [2]:
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('wordnet', quiet=True)     
nltk.download('omw-1.4', quiet=True) 
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

Create **stopwords** and **lemmatizer** instance/object

In [3]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

Create **cleaning** function

In [4]:

def clean_text(text, max_length=30):
    
    text = emoji.demojize(text)

    text = text.lower().strip()

    text = re.sub(r'[^a-z\s]', '', re.sub(r'\b([a-z])\1+\b', '', text))

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word.isalpha()]

    tokens = [word for word in tokens if word not in stop_words]

    tokens = [lemmatizer.lemmatize(word, pos='v') for word in tokens]

    tokens = [word for word in tokens if len(word) <= max_length]

    return " ".join(tokens)

Apply the cleaning function to dataset

In [5]:
df['clean_text'] = df['text'].apply(clean_text)

Check result

In [6]:
df[['text', 'clean_text']].head()

,text,clean_text
0,oh my gosh,oh gosh
1,"trouble sleeping, confused mind, restless hear...",trouble sleep confuse mind restless heart tune
2,"All wrong, back off dear, forward doubt. Stay ...",wrong back dear forward doubt stay restless re...
3,I've shifted my focus to something else but I'...,ive shift focus something else im still worry
4,"I'm restless and restless, it's been a month n...",im restless restless month boy mean

Save the **cleaned** and **preprocessed** dataset

In [7]:
df.to_csv('mental_health_dataset_cleaned.csv', index=False)